services:
  traccar-migrate:
    build: .
    image: registry.baileys.dev/traccar-migrate
    restart: unless-stopped
    environment:
      ADDR: ":8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traccar-migrate.rule=Host(`traccar-migrate.lab.baileys.dev`)
      - traefik.http.services.traccar-migrate.loadbalancer.server.port=8080
